# Generated by Django 4.1.2 on 2022-11-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train_test_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('pcp', models.CharField(max_length=10)),
                ('alarm', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
                ('etc', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'train_test_data',
            },
        ),
    ]
