# Generated by Django 4.1.2 on 2022-11-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=600)),
                ('a_value', models.CharField(max_length=400)),
                ('q_id', models.CharField(max_length=600)),
                ('a_class', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='a_class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_class', models.CharField(max_length=500)),
                ('q_class', models.CharField(max_length=500)),
                ('a_value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=10)),
                ('prob_free', models.CharField(max_length=300)),
                ('prob_category', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
        migrations.CreateModel(
            name='answer_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=60)),
                ('a_value', models.CharField(max_length=400)),
                ('q_id', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'answer_db',
            },
        ),
        migrations.CreateModel(
            name='cc_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cc_id', models.CharField(max_length=2000)),
                ('cc_lead_value', models.CharField(max_length=2000)),
                ('cc_value', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='q_bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q_id', models.CharField(max_length=500)),
                ('q_value', models.CharField(max_length=500)),
                ('q_type', models.CharField(max_length=600)),
                ('q_class', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='q_class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q_class', models.CharField(max_length=500)),
                ('q_value', models.CharField(max_length=500)),
                ('q_type', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='question_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=200)),
                ('q_value', models.CharField(max_length=400)),
                ('question_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'question_db',
            },
        ),
        migrations.CreateModel(
            name='question_suggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=60)),
                ('q_id', models.CharField(max_length=200)),
                ('q_value', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'question_suggest',
            },
        ),
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=2000)),
                ('output', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.CreateModel(
            name='train_test_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('pcp', models.CharField(max_length=10)),
                ('alarm', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
                ('etc', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'train_test_data',
            },
        ),
    ]
