# Generated by Django 4.1.2 on 2022-11-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=200)),
                ('q_value', models.CharField(max_length=400)),
                ('question_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'question_db',
            },
        ),
    ]
