# Generated by Django 4.1.2 on 2022-11-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0002_delete_train_test_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question_db',
        ),
    ]
