# Generated by Django 4.1.2 on 2022-11-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0002_question_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question_db',
        ),
    ]
