# Generated by Django 4.1.2 on 2022-11-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0003_delete_question_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agenda',
        ),
        migrations.DeleteModel(
            name='answer_db',
        ),
        migrations.DeleteModel(
            name='cc_db',
        ),
        migrations.DeleteModel(
            name='question_suggest',
        ),
        migrations.DeleteModel(
            name='train',
        ),
        migrations.AddField(
            model_name='a_bank',
            name='a_note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
