# Generated by Django 4.1.2 on 2022-11-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0003_delete_question_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000)),
            ],
        ),
    ]
