# Generated by Django 4.1.2 on 2022-11-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0004_delete_agenda_delete_answer_db_delete_cc_db_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_bank',
            name='a_lvl',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
