# Generated by Django 4.1.2 on 2022-11-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0005_a_bank_a_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_bank',
            name='a_dup',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
