# Generated by Django 4.1.2 on 2022-11-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0006_a_bank_a_dup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a_bank',
            old_name='a_dup',
            new_name='a_parent',
        ),
    ]
