# Generated by Django 4.1.2 on 2022-12-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0008_alter_a_bank_a_id_alter_a_class_a_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_bank',
            name='a_id',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='a_class',
            name='a_class',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='q_bank',
            name='q_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='q_class',
            name='q_class',
            field=models.CharField(max_length=500),
        ),
    ]
