# Generated by Django 4.1.2 on 2022-12-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0009_alter_a_bank_a_id_alter_a_class_a_class_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a_bank',
        ),
        migrations.DeleteModel(
            name='a_class',
        ),
        migrations.DeleteModel(
            name='q_bank',
        ),
        migrations.DeleteModel(
            name='q_class',
        ),
    ]
