# Generated by Django 4.1.2 on 2022-12-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1782', '0010_delete_a_bank_delete_a_class_delete_q_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=600)),
                ('a_value', models.CharField(max_length=400)),
                ('q_id', models.CharField(max_length=600)),
                ('a_class', models.CharField(max_length=500)),
                ('a_note', models.CharField(max_length=1000, null=True)),
                ('a_lvl', models.CharField(max_length=20, null=True)),
                ('a_parent', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='a_class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_class', models.CharField(max_length=500)),
                ('q_class', models.CharField(max_length=500)),
                ('a_value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='q_bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q_id', models.CharField(max_length=500)),
                ('q_value', models.CharField(max_length=500)),
                ('q_type', models.CharField(max_length=600)),
                ('q_class', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='q_class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q_class', models.CharField(max_length=500)),
                ('q_value', models.CharField(max_length=500)),
                ('q_type', models.CharField(max_length=600)),
            ],
        ),
    ]
