# Generated by Django 4.1.2 on 2022-12-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_bank',
            name='a_parent',
        ),
    ]
