# Generated by Django 4.1.2 on 2022-12-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0012_remove_a_bank_a_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_class',
            name='a_class',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
