# Generated by Django 4.1.2 on 2022-12-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1782', '0014_alter_q_class_q_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_bank',
            name='a_id',
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='q_bank',
            name='q_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
